### ISSUE TITLE
tvOS & iOS 支援截圖時取得影片內容

### ISSUE THREAD

**Issue by shaneCSW** [mybigday/react-native-screen-capture#3]
To: Launcher
Platform: iOS, tvOS

## Description
 - 現在 tvOS & iOS 畫面中有影片時，在截圖畫面上，該影片區塊會變成透明，或不顯示
 - 希望支援截圖時取得影片內容
    - 包含影片、相機畫面、影像串流
    - 若可以，也支援截圖網頁內的影片
 - 若有多圖層結構選染時，當前顯示的內容希望都可以正確截圖

**Comment by shaneCSW** [comment]
@jhen0409 @hans00 ，請問這有機會在 2.17 處理嗎？

**Comment by hans00** [comment]
fix in 81f5581
